
#' Create and display a summary table
#' 
#' Generates a formatted table from data returned by \code{get_*()} acessor 
#' functions, using the \pkg{gt} package. The table can be displayed in the
#' Viewer pane, printed to the console, and optionally saved to file.
#' 
#' @param data A data frame containing extracted model results, returned by one 
#'   of the package \code{get_*()} functions.
#' @param show Optional. Character string specifying how the table should be
#'   displayed. Possible values are:
#'   \itemize{
#'     \item \code{"html"}: displays the table as an HTML file in the Viewer.
#'     \item \code{"png"}: displays the table as a PNG image in the Viewer.
#'     \item \code{"console"}: prints the raw data frame to the console.
#'     \item \code{NULL}: no display output.
#'   }
#' @param save Optional. Character string specifying the output format used to
#'   save the table. Possible values are:
#'   \itemize{
#'     \item \code{"html"}: saves the table as an HTML file.
#'     \item \code{"png"}: saves the table as a PNG image.
#'     \item \code{"pdf"}: saves the table as a PDF file.
#'     \item \code{"xlsx"}: saves the raw data as an Excel file.
#'     \item \code{NULL}: no file is saved.
#'   }
#' @param filename Optional. Character string specifying the output file name
#'   without extension. Defaults to \code{"summary_table"}.
#' @param digits A integer indicating the number of decimals places to display. 
#'   Defaults to 4.
#' 
#' @return
#' Invisibly returns a formatted \code{gt} table object.
#' 
#' @details
#' The generated table automatically formats column labels in bold and applies
#' alternating row background colors to improve readability.
#' 
#' When \code{show} is enabled, temporary files are generated and displayed
#' using the RStudio Viewer pane. If \code{show = "console"}, the raw input
#' data frame is printed instead of the formatted table.
#' 
#' If \code{save = "xlsx"}, the raw input data frame is exported using
#' \pkg{openxlsx}; otherwise, the formatted \pkg{gt} table is exported using
#' \code{gtsave()}.
#' 
#' This function is designed as a general-purpose table formatter for outputs
#' generated by package extraction functions.
#' 
#' @export
#' @importFrom gt gtsave
#' @importFrom rstudioapi viewer isAvailable
#' @importFrom openxlsx write.xlsx
#' @importFrom utils browseURL
summary_table <- function(data, show = "html", save = NULL, 
  filename = "summary_table", digits = 4) {
  table <- .default_table(data, digits = digits)
  
  if (!is.null(show)) {
    ext <- switch(
      show,
      html = ".html",
      png  = ".png",
      console  = "console",
      stop("Invalid show type")
    )
    if (ext != "console") {
      file <- tempfile(fileext = ext)
      gtsave(table, file)
      if (isAvailable()) {
        viewer(file)
      } else {
        browseURL(file)
      }
    }
    else {
      print(data)
    }
  }

  if (!is.null(save)) {
    ext <- switch(
      save,
      png  = ".png",
      html = ".html",
      pdf  = ".pdf",
      xlsx = ".xlsx",
      stop("Invalid save type")
    )

    file <- paste0(filename, ext)
    if (ext != ".xlsx") {
      gtsave(table, file)
    }
    else {
      write.xlsx(data, file)
    }
  }
}

#' Create a default formatted gt table
#' 
#' Internal helper function used to generate consistently formatted \pkg{gt} 
#' tables across package outputs.
#' 
#' @param data A data frame to be formatted as a \pkg{gt} table.
#' @param digits A integer indicating the number of decimals places to display.
#' 
#' @return
#' A formatted \code{gt} table object with bold column labels and alternating
#' row background colors.
#' 
#' @details
#' This function applies a default visual style to tables, including bold
#' column headers and zebra-striping for improved readability.
#' 
#' @keywords internal
#' @importFrom gt gt tab_style cell_text cells_body cell_fill html fmt_number
#' cells_column_labels cols_label
#' @importFrom dplyr where
.default_table <- function(data, digits) {

  label_map <- list(
    bmsy = html("B<sub>MSY</sub>"),
    fmsy = html("F<sub>MSY</sub>"),
    msy  = "MSY",
    bb0 = html("b/b<sub>0</sub>"),
    k = "K"
  )

  labels <- label_map[names(label_map) %in% names(data)]
  
  table <- gt(data = data) %>%
    fmt_number(
      columns = where(is.numeric),
      decimals = digits
    ) %>%
    cols_label(.list = labels) %>%
    tab_style(
      style = cell_text(weight = "bold"),
      locations = cells_column_labels()
    ) %>%
    tab_style(
      style = cell_fill(color = "#f7f7f7"),
      locations = cells_body(
        rows = seq_len(nrow(data)) %% 2 == 0
      )
    )
  return(table)
}